spring:
 datasource:
  url: jdbc:mysql://localhost:3306/NL2SQLGen
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.entity
 configuration:
  map-underscore-to-camel-case: true
  cache-enabled: true
  lazy-loading-enabled: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 可选，打印SQL日志

milvus:
  url: 172.20.192.137
  port: 19530

deepseek:
 url: 172.20.192.137
 port: 5001

simcse:
 url: http://172.20.192.137
 port: 5000

server:
 port: 8080
